# Generated by Django 5.1.7 on 2025-03-31 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='author',
        ),
        migrations.RemoveField(
            model_name='story',
            name='content',
        ),
        migrations.RemoveField(
            model_name='story',
            name='created_at',
        ),
        migrations.AddField(
            model_name='story',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='genres',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='url',
            field=models.URLField(default='https://example.com'),
        ),
    ]
