# Generated by Django 5.1.7 on 2025-03-31 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0002_remove_story_author_remove_story_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='url',
            field=models.URLField(default='unknown'),
        ),
    ]
